title: Logsource to LogName mappings for PowerShell backend
order: 20
backends:
  - powershell
logsources:
  windows-application:
    product: windows
    service: application
    conditions:
      LogName: 'Application'
  windows-security:
    product: windows
    service: security
    conditions:
      LogName: 'Security'
  windows-system:
    product: windows
    service: system
    conditions:
      LogName: 'System'
  windows-sysmon:
    product: windows
    service: sysmon
    conditions:
      LogName: 'Microsoft-Windows-Sysmon/Operational'
  windows-powershell:
    product: windows
    service: powershell
    conditions:
      LogName:
        - 'Microsoft-Windows-PowerShell/Operational'
        - 'PowerShellCore/Operational'
  windows-classicpowershell:
    product: windows
    service: powershell-classic
    conditions:
      LogName: 'Windows PowerShell'
  windows-taskscheduler:
    product: windows
    service: taskscheduler
    conditions:
      LogName: 'Microsoft-Windows-TaskScheduler/Operational'
  windows-wmi:
    product: windows
    service: wmi
    conditions:
      LogName: 'Microsoft-Windows-WMI-Activity/Operational'
  windows-dns-server:
    product: windows
    service: dns-server
    conditions:
      LogName: 'DNS Server'
  windows-dns-server-audit:
    product: windows
    service: dns-server-audit
    conditions:
      LogName: 'Microsoft-Windows-DNS-Server/Audit'
  windows-driver-framework:
    product: windows
    service: driver-framework
    conditions:
      LogName: 'Microsoft-Windows-DriverFrameworks-UserMode/Operational'
  windows-ntlm:
    product: windows
    service: ntlm
    conditions:
      LogName: 'Microsoft-Windows-NTLM/Operational'
  windows-dhcp:
    product: windows
    service: dhcp
    conditions:
      LogName: 'Microsoft-Windows-DHCP-Server/Operational'
  windows-defender:
    product: windows
    service: windefend
    conditions:
      LogName: 'Microsoft-Windows-Windows Defender/Operational'
  windows-applocker:
    product: windows
    service: applocker
    conditions:
      LogName:
        - 'Microsoft-Windows-AppLocker/MSI and Script'
        - 'Microsoft-Windows-AppLocker/EXE and DLL'
        - 'Microsoft-Windows-AppLocker/Packaged app-Deployment'
        - 'Microsoft-Windows-AppLocker/Packaged app-Execution'
  windows-msexchange-management:
    product: windows
    service: msexchange-management
    conditions:
      LogName: 'MSExchange Management'
  windows-printservice-admin:
    product: windows
    service: printservice-admin
    conditions:
      LogName: 'Microsoft-Windows-PrintService/Admin'
  windows-printservice-operational:
    product: windows
    service: printservice-operational
    conditions:
      LogName: 'Microsoft-Windows-PrintService/Operational'
  windows-terminalservices-localsessionmanager-operational:
    product: windows
    service: terminalservices-localsessionmanager
    conditions:
      LogName: 'Microsoft-Windows-TerminalServices-LocalSessionManager/Operational'
  windows-codeintegrity-operational:
    product: windows
    service: codeintegrity-operational
    conditions:
      LogName: 'Microsoft-Windows-CodeIntegrity/Operational'
  windows-smbclient-security:
    product: windows
    service: smbclient-security
    conditions:
      LogName: 'Microsoft-Windows-SmbClient/Security'
  windows-firewall-advanced-security:
    product: windows
    service: firewall-as
    conditions:
      LogName: 'Microsoft-Windows-Windows Firewall With Advanced Security/Firewall'
  windows-bits-client:
    product: windows
    service: bits-client
    conditions:
      LogName: 'Microsoft-Windows-Bits-Client/Operational'
  windows-security-mitigations:
    product: windows
    service: security-mitigations
    conditions:
      LogName:
        - 'Microsoft-Windows-Security-Mitigations/Kernel Mode'
        - 'Microsoft-Windows-Security-Mitigations/User Mode'
  windows-diagnosis:
    product: windows
    service: diagnosis-scripted
    conditions:
      LogName: 'Microsoft-Windows-Diagnosis-Scripted/Operational'
  windows-shell-core:
    product: windows
    service: shell-core
    conditions:
      LogName: 'Microsoft-Windows-Shell-Core/Operational'
  windows-openssh:
    product: windows
    service: openssh
    conditions:
      LogName: 'OpenSSH/Operational'
  windows-ldap-debug:
    product: windows
    service: ldap_debug
    conditions:
      LogName: 'Microsoft-Windows-LDAP-Client/Debug'
  windows-bitlocker:
    product: windows
    service: bitlocker
    conditions:
      LogName: 'Microsoft-Windows-BitLocker/BitLocker Management'
  windows-vhdmp-operational:
    product: windows
    service: vhdmp
    conditions:
      LogName: 'Microsoft-Windows-VHDMP/Operational'
  windows-appxdeployment-server:
    product: windows
    service: appxdeployment-server
    conditions:
      LogName: 'Microsoft-Windows-AppXDeploymentServer/Operational'
